# Generated by Django 5.2.7 on 2025-10-13 14:38

import django.core.validators
import django.db.models.deletion
import src.tiny_voucher.models.audil_log
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CampaignModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "deleted_by",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "PERCENTAGE"),
                            ("FIXED_VALUE", "FIXED"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0–100) or fixed value, depending on discount_type.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("total_vouchers", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
            ],
            options={
                "db_table": "campaign",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AuditLogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(db_index=True, max_length=255)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("CAMPAIGN", "CAMPAIGN"),
                            ("VOUCHER", "VOUCHER"),
                            ("VOUCHER_REDEMPTION", "VOUCHER_REDEMPTION"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("object_repr", models.CharField(max_length=255)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ADDITION", "ADDITION"),
                            ("CHANGE", "CHANGE"),
                            ("DELETION", "DELETION"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ADMIN", "ADMIN"),
                            ("API", "API"),
                            ("COMMAND", "COMMAND"),
                        ],
                        db_index=True,
                        default="API",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="User with id 0 [Sys]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=src.tiny_voucher.models.audil_log.metadata_default
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_obj_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VoucherModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "deleted_by",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True
                    ),
                ),
                ("is_redeemed", models.BooleanField(default=False)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="tiny_voucher.campaignmodel",
                    ),
                ),
            ],
            options={
                "db_table": "voucher",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VoucherRedemptionModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "deleted_by",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "redeemed_by",
                    models.CharField(
                        help_text="Identifier of the user or entity that redeemed the voucher.",
                        max_length=150,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "voucher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemption",
                        to="tiny_voucher.vouchermodel",
                    ),
                ),
            ],
            options={
                "db_table": "voucher_redemptions",
                "ordering": ["-redeemed_at", "-id"],
            },
        ),
    ]
